// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type OrderReq struct {
	OrderId string `path:"orderId"` // 从 URL 路径中获取订单号
}

type OrderResp struct {
	OrderId     string `json:"orderId"`
	Status      string `json:"status"`
	OwnerName   string `json:"ownerName"`
	OwnerSecret string `json:"ownerSecret"`
}
