// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Number   string `json:"number"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Number   string `json:"number"` // 学号/工号，作为唯一标识
}

type RegisterResp struct {
	Message string `json:"message"`
}

type UserInfoResp struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Number string `json:"number"`
}
